# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a33f88b2fb6e732e8d082298a56ef24aa06974823b290bb2fc66024ea91bfa0da90bc1c55a1f8133e0e39bb5f1d9b6e655ac0ab0a07ae6b390540f199aa82ed

test:
  secret_key_base: b7148d7da2f4595d632c1208cbf5acc75bb56782eca16b841ba3479bb16b0ea21b190f9985cd70485dca6c2e58bb6d6ff23d72877af8ab30e4361091ad3b870a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
